project:
  type: book

book:
  title: "book-bug"
  author: "Ella Kaye"
  chapters:
    - index.qmd
    - references.qmd
  appendices:
    - code.qmd
    
bibliography: references.bib

format:
  pdf:
    documentclass: scrreprt
    keep-tex: true


